### ISSUE TITLE
chaim's account links from facebook email, but gets this error saving employer profile

### ISSUE THREAD

**Issue by jcii** [SavageLearning/Machete#292]
"   at Machete.Data.MacheteContext.Commit()
   at Machete.Service.ServiceBase`1.Create(T record, String user)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClassc.<GetExecutor>b__6(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"

**Comment by esteban-gs** [comment]
FB Auth. failed on Firefox and Chrome:

Chrome:
![image](https://user-images.githubusercontent.com/26440947/35652009-bf971d26-06d9-11e8-8564-16b2134954af.png)
version:
![image](https://user-images.githubusercontent.com/26440947/35652021-ce756334-06d9-11e8-92ed-8a5a98954ef7.png)

FireFox:
![image](https://user-images.githubusercontent.com/26440947/35652031-d67ada32-06d9-11e8-897d-9229edfc1cc0.png)
version: 
![image](https://user-images.githubusercontent.com/26440947/35652051-ede4f234-06d9-11e8-8dc0-88c4d9431f9c.png)

**Comment by jcii** [comment]
havent seen this in a while
