### ISSUE TITLE
chaim1221/Machete: Toggling allowDefault in config does not work. This does not block a production deployment.

### ISSUE THREAD

**Issue by chaim1221** [SavageLearning/Machete#444]
```
Unhandled Exception: System.UnauthorizedAccessException: Requested default provider, but default not allowed. You have probably misconfigured a production host. Contact your administrator for assistance.
   at Machete.Data.Tenancy.TenantIdentificationService.GetCurrentTenant(HttpContext context) in /home/appveyor/projects/machete-k8wo2/Machete.Data/Tenancy/TenantIdentificationService.cs:line 31
   at Machete.Data.Tenancy.TenantService.GetCurrentTenant() in /home/appveyor/projects/machete-k8wo2/Machete.Data/Tenancy/TenantService.cs:line 28
   at Machete.Data.MacheteContext..ctor(DbContextOptions`1 options, ITenantService tenantService) in /home/appveyor/projects/machete-k8wo2/Machete.Data/MacheteContext.cs:line 63
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Machete.Web.StartupConfiguration.SeedUsersAsync(IWebHost webhost) in /home/appveyor/projects/machete-k8wo2/Machete.Web/StartupConfiguration.cs:line 70
   at Machete.Web.Program.Main(String[] args) in /home/appveyor/projects/machete-k8wo2/Machete.Web/Program.cs:line 24
   at Machete.Web.Program.<Main>(String[] args)
Aborted (core dumped)
```

This line should preclude this from happening:

https://github.com/chaim1221/Machete/blob/feature/multi-tenancy-sqlserver/Machete.Data/Tenancy/TenantService.cs#L39

(but doesn't)

**Comment by chaim1221** [comment]
This is now working. I don't remember what the issue was, but there is no way to login to a `"default"` session now, no matter what login you use. The page automatically redirects to V2 signin, and V2 signin fails.
