### ISSUE TITLE
chaim1221 TransportRule mapping error (V2)

### ISSUE THREAD

**Issue by chaim1221** [SavageLearning/Machete#471]
```
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLNH836BQE3J", Request id "0HLNH836BQE3J:00000007": An unhandled exception was thrown by the application.
AutoMapper.AutoMapperMappingException: Error mapping types.

Mapping types:
TransportRule -> TransportRule
Machete.Domain.TransportRule -> Machete.Web.ViewModel.Api.TransportRule

Type Map configuration:
TransportRule -> TransportRule
Machete.Domain.TransportRule -> Machete.Web.ViewModel.Api.TransportRule

Destination Member:
costRules
 ---> System.InvalidOperationException: Error generated for warning 'Microsoft.EntityFrameworkCore.Infrastructure.DetachedLazyLoadingWarning: An attempt was made to lazy-load navigation property 'costRules' on detached entity of type 'TransportRuleProxy'. Lazy-loading is not supported for detached entities or entities that are loaded with 'AsNoTracking()'.'. This exception can be suppressed or logged by passing event ID 'CoreEventId.DetachedLazyLoadingWarning' to the 'ConfigureWarnings' method in 'DbContext.OnConfiguring' or 'AddDbContext'.
   at Microsoft.EntityFrameworkCore.Diagnostics.EventDefinition`2.Log[TLoggerCategory](IDiagnosticsLogger`1 logger, WarningBehavior warningBehavior, TParam1 arg1, TParam2 arg2, Exception exception)
   at Microsoft.EntityFrameworkCore.Internal.CoreLoggerExtensions.DetachedLazyLoadingWarning(IDiagnosticsLogger`1 diagnostics, DbContext context, Object entityType, String navigationName)
   at Microsoft.EntityFrameworkCore.Internal.LazyLoader.ShouldLoad(Object entity, String navigationName, NavigationEntry& navigationEntry)
   at Microsoft.EntityFrameworkCore.Internal.LazyLoader.Load(Object entity, String navigationName)
   at Microsoft.EntityFrameworkCore.Proxies.Internal.LazyLoadingInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.TransportRuleProxy.get_costRules()
   at lambda_method(Closure , TransportRule , TransportRule , ResolutionContext )
   --- End of inner exception stack trace ---
   at lambda_method(Closure , TransportRule , TransportRule , ResolutionContext )
   at AutoMapper.Mapper.AutoMapper.IMapper.Map[TSource,TDestination](TSource source) in C:\projects\automapper\src\AutoMapper\Mapper.cs:line 233
   at Machete.Web.Controllers.Api.TransportRulesController.<Get>b__3_0(TransportRule e) in /Users/celiyah/Code/machete/web/Machete.Web/Controllers/Api/TransportRulesController.cs:line 36
```
Steps: V2 -> Create Profile -> Sent to work order; happens there

**Comment by chaim1221** [comment]
chaim [6:33 PM]
ugh... so... there's a lazy-loading error on getting the TransportCostRules as part of the TransportRules. I can fix that by ignoring the cost rules (during mapping), but then lo and behold, when I finally get to the part of the form that requires them, they are missing.

however if I then undo the .Ignore() rule, and get the TransportCostRules, they are loaded into the UI and they do not go away, therefore I cannot trigger the bug again, which makes it hard to diagnose.

sometimes the error just doesn't happen at all, in an incognito window
also PayPal... the paypal window opens, nothing happens
once I saw a client ID rejection message, it hasn't reappeared
