### ISSUE TITLE
chaim1221 admins cannot create profiles/orders if they logged in through v1

### ISSUE THREAD

**Issue by chaim1221** [SavageLearning/Machete#472]
```
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLNH7UIRJDV4", Request id "0HLNH7UIRJDV4:00000001": An unhandled exception was thrown by the application.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Machete.Domain.Record.createdByUser(String user) in /home/appveyor/projects/machete-k8wo2/Machete.Domain/Entities/Record.cs:line 53
   at Machete.Service.ServiceBase`1.Create(T record, String user) in /home/appveyor/projects/machete-k8wo2/Machete.Service/shared/ServiceBase.cs:line 112
   at Machete.Service.EmployerService.Create(Employer record, String user) in /home/appveyor/projects/machete-k8wo2/Machete.Service/EmployerService.cs:line 64
   at Machete.Web.Controllers.Api.EmployersController.ProfilePut(Employer viewmodel) in /home/appveyor/projects/machete-k8wo2/Machete.Web/Controllers/Api/EmployersController.cs:line 180
```

The missing piece of information is "UserEmail" which is taken from a claim, see MacheteApiController ln. 11, the claims only get written if the user logs in via V2. Will not affect employers but may affect staff hiring workers.

**Comment by chaim1221** [comment]
![image](https://user-images.githubusercontent.com/3819970/59577369-5a7b0e00-9078-11e9-9ce3-d07f2c759d59.png)

**Comment by chaim1221** [comment]
This is where the claims it's looking for are populated from the V2 user:

https://github.com/chaim1221/Machete/blob/master/Machete.Web/Controllers/Api/Abstracts/MacheteApiController.cs#L11

**Comment by chaim1221** [comment]
as indicated by #490 this is a blocker for testing, so I'm going to raise the status.

**Comment by chaim1221** [comment]
![image](https://user-images.githubusercontent.com/3819970/60751760-661f6d80-9f70-11e9-916a-16b6568a16d1.png)

**Comment by chaim1221** [comment]
Logged in as admin through v1.
