### ISSUE TITLE
PayPal takes money, but database is not updated with amount; app asks for more

### ISSUE THREAD

**Issue by chaim1221** [SavageLearning/Machete#490]
test-casa.machete/v2 is not writing response to db.

esteban.gs [9:22 PM]
paypal API I imagine.

esteban.gs [9:24 PM]
took my money, still asking for more :disappointed:

**Comment by chaim1221** [comment]
![image](https://user-images.githubusercontent.com/3819970/60482829-ecbe0d00-9c47-11e9-89de-f72d09765e17.png)

![image](https://user-images.githubusercontent.com/3819970/60482837-f21b5780-9c47-11e9-8be1-b0128d2d66ea.png)

**Comment by esteban-gs** [comment]
@chaim1221  So, the transaction didn't go through. I didn't get an email and the transaction is not in the Paypal report.

**Comment by chaim1221** [comment]
So I don't have the database records anymore because I replaced them on the last deploy. But I'm pretty sure this was working (see images at #413) in 1.14.65, so I am not sure what happened. I don't have anything available to test with right now, cash-wise, but I can look at the configuration and see if I can find something.

**Comment by chaim1221** [comment]
```
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Machete.Domain.Record.updatedByUser(String user) in /home/appveyor/projects/machete-k8wo2/Machete.Domain/Entities/Record.cs:line 46
   at Machete.Service.ServiceBase`1.Save(T record, String user) in /home/appveyor/projects/machete-k8wo2/Machete.Service/shared/ServiceBase.cs:line 137
   at Machete.Service.WorkOrderService.Save(WorkOrder workOrder, String user) in /home/appveyor/projects/machete-k8wo2/Machete.Service/WorkOrderService.cs:line 305
   at Machete.Web.Controllers.Api.OnlineOrdersController.PaypalExecute(Int32 orderID, PaypalPayment data) in /home/appveyor/projects/machete-k8wo2/Machete.Web/Controllers/Api/OnlineOrdersController.cs:line 149
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
info: Microsoft.AspNetCore.Cors.Infrastructure.CorsService[5]
      CORS policy execution failed.
info: Microsoft.AspNetCore.Cors.Infrastructure.CorsService[6]
      Request origin https://test-casa.machetessl.org does not have permission to access the resource.
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[3]
      An exception was thrown attempting to execute the error handler.
System.InvalidOperationException: The SPA default page middleware could not return the default page '/index.html' because it was not found, and no other middleware handled the request.
Your application is running in Production mode, so make sure it has been published, or that you have built your SPA manually. Alternatively you may wish to switch to the Development environment.

   at Microsoft.AspNetCore.SpaServices.SpaDefaultPageMiddleware.<>c__DisplayClass0_0.<Attach>b__1(HttpContext context, Func`1 next)
   at Microsoft.AspNetCore.Builder.UseExtensions.<>c__DisplayClass0_1.<Use>b__1(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLNS7TGI6E7B", Request id "0HLNS7TGI6E7B:00000001": An unhandled exception was thrown by the application.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Machete.Domain.Record.updatedByUser(String user) in /home/appveyor/projects/machete-k8wo2/Machete.Domain/Entities/Record.cs:line 46
   at Machete.Service.ServiceBase`1.Save(T record, String user) in /home/appveyor/projects/machete-k8wo2/Machete.Service/shared/ServiceBase.cs:line 137
   at Machete.Service.WorkOrderService.Save(WorkOrder workOrder, String user) in /home/appveyor/projects/machete-k8wo2/Machete.Service/WorkOrderService.cs:line 305
   at Machete.Web.Controllers.Api.OnlineOrdersController.PaypalExecute(Int32 orderID, PaypalPayment data) in /home/appveyor/projects/machete-k8wo2/Machete.Web/Controllers/Api/OnlineOrdersController.cs:line 149
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
65.50.184.110 - - [04/Jul/2019:23:30:59 +0000] "POST /api/onlineorders/99771/paypalexecute HTTP/1.1" 500 0 "https://test-casa.machetessl.org/V2/my-work-orders/99771" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36" "-"
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 133.109ms 500 

```

I am experiencing the same issue on test-casa.

**Comment by chaim1221** [comment]
So... I think I know what is happening. It's #472 . I am going to prove that out and fix it, because it appears to be a blocker for testing.

**Comment by chaim1221** [comment]
![image](https://user-images.githubusercontent.com/3819970/60690173-10689980-9e7a-11e9-95ba-225e2e1f69d9.png)

![image](https://user-images.githubusercontent.com/3819970/60690213-54f43500-9e7a-11e9-8cd3-791fa765b966.png)

Closing as duplicate.
