### ISSUE TITLE
Dispatch Work Assignment search broken

### ISSUE THREAD

**Issue by esteban-gs** [SavageLearning/Machete#573]
on 1.14.186
**Reproduce:**
- go to dispatch, type into the search field. 
- Search fails

Found bug after 1.14.186, but issue may have been present on previous releases.
log: 
````fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method(Closure , TransparentIdentifier`2 )
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.GetCount(Boolean onlyIfCheap)
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ResultEnumerable`1.GetEnumerator()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_1`1.<CompileQueryCore>b__0(QueryContext qc)
   at System.Linq.Queryable.Count[TSource](IQueryable`1 source)
   at Machete.Service.WorkAssignmentService.GetIndexView(viewOptions o) in /home/comsat61/Code/Machete/Machete.Service/WorkAssignmentService.cs:line 119
   at Machete.Web.Controllers.WorkAssignmentController.AjaxHandler(jQueryDataTableParam param) in /home/comsat61/Code/Machete/Machete.Web/Controllers/Legacy/WorkAssignmentController.cs:line 96

**Comment by esteban-gs** [comment]
The issue is fixed when removing both lookup lines `sk.text_EN.Contains(o.sSearch)` lines in the IndexViewBase.cs `search()` Method.

https://github.com/SavageLearning/Machete/blob/7c2f3ed2d71658cc178c3650849a2b7585188c8f/Machete.Service/shared/IndexViewBase.cs#L53
