### ISSUE TITLE
Facebook Login not working

### ISSUE THREAD

**Issue by esteban-gs** [SavageLearning/Machete#673]
### Reproduce
Login with a non admin Facebook account. Login fails silently. You will notice that email is not part of the login permissions.

Logs throw a Viewmodel  exception "email is required"
``` log
dotnet_1     | fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
dotnet_1     |       An unhandled exception has occurred while executing the request.
dotnet_1     | System.ArgumentNullException: Value cannot be null. (Parameter 'email')
dotnet_1     |    at Microsoft.AspNetCore.Identity.UserManager`1.FindByEmailAsync(String email)
dotnet_1     |    at Machete.Web.Controllers.Api.Identity.IdentityController.SigninByEmailAsync(HttpResponseMessage tokenResponse, HttpClient httpClient, String provider, String redirectUri) in /admin/Machete.Web/Controllers/Api/Identity/IdentityController.cs:line 215
```

**Comment by esteban-gs** [comment]
According to the [reference](https://developers.facebook.com/docs/graph-api/reference/user/), email won't be returned is a user has no confirmed email. Will need to return a notice to user when this is the case and ask for alternate sign-in method.
